server:
  port: 8081
spring:
  application:
    name: meetshop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meetshop?useSSL=false&serverTimezone=UTC
    username: root
    password: G200410115812
  redis:
    host: 47.104.195.63
    port: 6379
    password: G200410115812
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.meetshop.entity # 别名扫描包
logging:
  level:
    com.meetshop: debug